"""Write transparent measured-results tables; recommendation is added after review."""
import csv,json,sys,statistics
from pathlib import Path
b=Path(sys.argv[1]);a=b/'analysis'
def read(name):return json.loads((a/name).read_text())
def csvrows(name):
 with (a/name).open() as f:return list(csv.DictReader(f))
c=read('primitive-curves.json');sen=read('order-sensitivity.json');count=read('counts.json');audit=read('slot-audit.json');contr=csvrows('runtime-contrasts.csv');cc=read('composite-curves.json');first=read('first-launch.json')
lines=['# Iteration threshold study: measured results','', 'Ten independently provisioned Linux/Windows host pairs. Per test/configuration: 10 first-launch observations, 100 development observations and 100 separate validation observations. Sample sizes 10–100 add one development observation per host at each step. Validation observations are never included in the development estimates.','',f"Recorded **{audit['physical_records']:,}** executions of **{audit['expected_slots']:,}** planned slots. Missing: {len(audit['missing'])}; unexpected: {len(audit['unexpected'])}; duplicate slots: {len(audit['duplicates'])}.",'', '| Cohort | Behaviors | Configurations | Cells |','|---|---:|---:|---:|','| Linux primitives | 13 | 8 | 104 |','| Windows primitives | 3 | 6 | 18 |','| Linux active composites | 30 | 8 | 240 |','| Windows active composites | 23 | 8 | 184 |','', 'Composites also have paired controls; Linux includes a negative program. Windows primitives currently cover empty, file I/O and spawn, without Rust. DNS onion is outside the qualified Windows composite scope.','', '## Mean volume and event composition','', 'Errors below compare development estimates with the independent validation set; validation is an estimate, not ground truth. Composition distance is total variation between mean per-run event-type proportions. The worst cell and the 95th percentile across cells answer different questions.','', '| Repetitions | Median volume error | 95th-percentile volume error | Worst volume error | Worst composition distance |','|---:|---:|---:|---:|---:|']
for r in c:lines.append(f"| {r['n']} | {r['volume_error_percent']['median']:.3f}% | {r['volume_error_percent']['p95']:.3f}% | {r['volume_error_percent']['max']:.3f}% | {r['composition_tv_pp']['max']:.3f} pp |")
if (a/'subsequent-run-ranges.json').exists():
 ranges=read('subsequent-run-ranges.json')
 lines+=['','## What varies between executions','', 'These ranges include all 200 subsequent-launch executions per complete cell, across development and validation. CV is the run-level standard deviation divided by the mean; it describes run variation, not uncertainty in a mean. No outliers were removed.','', '| Configuration / behavior | Events per run, range | Mean | Run-level CV |','|---|---:|---:|---:|']
 for r in sorted(ranges,key=lambda x:x['cv_percent'],reverse=True)[:6]:lines.append(f"| {r['config']} / {r['case']} | {r['min']}–{r['max']} | {r['mean']:.2f} | {r['cv_percent']:.2f}% |")
 for os in ('linux','windows'):
  rs=[r for r in ranges if r['os']==os]
  lines+=['',f"{os.capitalize()}: {sum(r['min']==r['max'] for r in rs)} of {len(rs)} cells had identical total event counts in all 200 subsequent executions. Identical totals do not imply identical event content."]
lines+=['','## Sensitivity to execution order','', 'These are resamples of actual observations, not additional physical executions. Within-host random subsets preserve balanced host contributions. Values show the 95th percentile of the worst-cell error across 500 randomized orderings. At n=100 every ordering contains all development observations, so ordering variability collapses by construction; this does not imply that a fresh 100-run sample would have no uncertainty.','', '| Repetitions | Worst volume error, order sensitivity | Worst composition distance, order sensitivity |','|---:|---:|---:|']
for r in sen:lines.append(f"| {r['n']} | {r['random_order_max_volume_p95']:.3f}% | {r['random_order_max_tv_p95']:.3f} pp |")
lines+=['','## Runtime comparisons','', 'Contrasts are paired by host and repetition. The adjusted contrast subtracts each runtime’s empty-program count first. Normalized errors use mean raw event volume as the denominator; this does not imply the same percentage error in a small runtime effect. Per-effect relative errors are supplied in runtime-contrasts.csv where the validation host-level interval excludes zero.','', '| Repetitions | Worst raw-contrast error | Worst adjusted-contrast error | Worst Jaccard error | Sign disagreements: raw / adjusted |','|---:|---:|---:|---:|---:|']
for n in range(10,101,10):
 rs=[r for r in contr if int(r['n'])==n];adj=[r for r in rs if r.get('adjusted_normalized_error_percent')]
 if not rs:continue
 raw=max(float(r['normalized_error_percent']) for r in rs);ad=max((float(r['adjusted_normalized_error_percent']) for r in adj),default=0);j=max(float(r['jaccard_error_pp']) for r in rs)
 flips=sum(r['reference_distinguishable']=='True' and r['sign_agrees']=='False' for r in rs);aflips=sum(r['adjusted_reference_distinguishable']=='True' and r['adjusted_sign_agrees']=='False' for r in adj)
 lines.append(f'| {n} | {raw:.3f}% | {ad:.3f}% | {j:.3f} pp | {flips} / {aflips} |')
lines+=['','Direction agreement is weaker than statistical sensitivity. The following counts show validation contrasts whose exploratory host-level interval excludes zero but whose development interval includes zero. These pointwise intervals are repeatability diagnostics, not the multiplicity-adjusted confirmatory tests. A zero count is not a power guarantee.','', '| Repetitions | Raw contrasts not resolved | Adjusted contrasts not resolved |','|---:|---:|---:|']
for n in range(10,101,10):
 rs=[r for r in contr if int(r['n'])==n]
 vals=[]
 for prefix in ('','adjusted_'):
  refs=[r for r in rs if r.get(prefix+'reference_distinguishable')=='True']
  vals.append(f"{sum(r.get(prefix+'development_distinguishable')!='True' for r in refs)} / {len(refs)}")
 lines.append(f'| {n} | {vals[0]} | {vals[1]} |')
lines+=['','## Detection outcomes','', 'Unknown or missing observations are not detector misses. Classification is always-alert, never-alert, mixed, or unknown among valid records. Agreement below is with the separate validation set. Raw per-case counts and exact pointwise intervals appear in composite-cells.csv.','', '| Repetitions | Platform / mode | Cells | Classification agreement | Mixed cells | Unknown or missing attempts |','|---:|---|---:|---:|---:|---:|']
for r in cc:lines.append(f"| {r['n']} | {r['os']} / {r['mode']} | {r['cells']} | {r['class_agreement']} | {r['mixed_development']} | {r['unknown_or_missing']} |")
if (a/'collection-durations.json').exists():
 timings=read('collection-durations.json')
 lines+=['','## Measured collection cost','', 'Wall-clock spans below cover all 21 collected blocks per host, including the initial-launch block and both data splits. Composite spans include fixture preparation, telemetry draining and rule evaluation. The interrupted Linux host is retained in the timing data but excluded from the uninterrupted-host median. Provisioning, archival and analysis are additional.','', '| Platform / cohort | Uninterrupted hosts | Median minutes for 21 blocks | Range, minutes |','|---|---:|---:|---:|']
 for os in ('linux','windows'):
  for cohort,key in [('primitives','primitive_wall_seconds'),('composites','composite_wall_seconds_including_fixture_and_evaluation')]:
   values=[r[key]/60 for r in timings if r['os']==os and key in r and (cohort=='primitives' or not r['collector_interruption'])]
   if values:lines.append(f'| {os} / {cohort} | {len(values)} | {statistics.median(values):.2f} | {min(values):.2f}–{max(values):.2f} |')
 lines+=['','For the currently qualified scope, each repetition across all configurations requires 122 primitive and 856 composite/control/negative executions. Uniform counts of 10, 40 and 100 therefore require 9,780, 39,120 and 97,800 measured executions, respectively, before warm-up or invalid-attempt replacements. Going from 40 to 100 multiplies measured execution work by 2.5. A cohort-specific design can use different primitive and composite counts; the cost is 122 × primitive count + 856 × composite count.','']
lines+=['','## First-launch effects','', 'The initial execution on each host is retained as a separate condition. This is compatible with the Chapter 3 warm-up provision; it does not remove ordinary program startup and teardown from subsequent runs.','', '| Test/configuration | Initial mean events | Validation mean events | Initial excess |','|---|---:|---:|---:|']
for r in sorted(first,key=lambda x:abs(x['first_excess_percent'] or 0),reverse=True)[:10]:lines.append(f"| {r['config']} / {r['case']} | {r['initial_mean']:.2f} | {r['subsequent_mean']:.2f} | {r['first_excess_percent']:.2f}% |")
lines+=['','## Accuracy targets are choices','', 'The following are the smallest measured counts meeting both targets for every complete primitive cell and remaining within target at all larger tested counts. They are descriptive stopping points, not guarantees or universal optima.','', '| Volume-error tolerance | Composition-distance tolerance | Smallest persistent count |','|---:|---:|---:|']
for r in read('thresholds.json'):
 if r['required_cell_fraction']==1:lines.append(f"| {r['volume_tolerance_percent']}% | {r['composition_tolerance_pp']} pp | {r['smallest_persistent_n'] or 'Not reached by 100'} |")
lines+=['','## What an unchanged alert outcome establishes','', 'The following is a binomial sensitivity model assuming independent, identically distributed executions. It is not an observed miss rate or evidence that a rate is zero. Host correlation can weaken the interpretation; this study also reports host-specific outcomes. Exact binomial interval methods are described by [NIST](https://www.itl.nist.gov/div898/handbook/prc/section2/prc241.htm).','', '| Repetitions | Upper one-sided 95% bound after zero opposite outcomes | Chance to see ≥1 if true rate is 1% | If true rate is 5% |','|---:|---:|---:|---:|']
for r in read('binary-sensitivity.json'):lines.append(f"| {r['n']} | {100*r['opposite_upper95_if_zero']:.2f}% | {100*r['chance_observe_at_least_one']['0.01']:.2f}% | {100*r['chance_observe_at_least_one']['0.05']:.2f}% |")
lines+=['','## Interpretation limits','', '- These are pilot data, not the confirmatory dissertation dataset.','- The count is per behavior/runtime configuration, with controls counted separately.','- The study estimates repeatability in the tested lab conditions. It is not a power guarantee for arbitrarily small runtime effects.','- Ten host instances, not hundreds of independent environments, support the host-level uncertainty estimates. The holdout contains separate executions on the same host fleet.','- More repetitions do not resolve a measurement-attribution defect. Unknowns must remain visible.','- The mean-confidence level and accuracy tolerances are explicit choices. [NIST explains the mean interval and its dependence on variance and sample size](https://www.itl.nist.gov/div898/handbook/eda/section3/eda352.htm).','', 'Collection plan: PROTOCOL.md plus PROTOCOL-analysis-clarification.md. Source, allocation, raw archives, SHA-256 receipts, normalized records, per-cell tables, and provenance checks accompany this report.','']
(b/'measured-results.md').write_text('\n'.join(lines));print(b/'measured-results.md')
