#include "core/engine.hpp"

#include <bpf/libbpf.h>
#include <signal.h>
#include <sys/wait.h>
#include <unistd.h>

#include <cerrno>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <set>
#include <vector>

#include "bpf/tmon_event.h"
#include "model/event.hpp"
#include "tmon.skel.h"  // generated by bpftool from tmon.bpf.c

namespace tmon {
namespace {

// State threaded through the libbpf ring-buffer callback. Holds the sink, the
// counters, and enough config to know when to stop.
struct PumpState {
  EventSink* sink = nullptr;
  Summary summary;
  std::set<std::uint32_t> pids;  // distinct tgids, for the process count
  std::uint64_t max_events = 0;  // 0 = unlimited
  bool stop = false;             // set once we hit max_events
};

// Translate the kernel wire record into the domain model.
Event ToEvent(const tmon_event& w) {
  Event e;
  switch (w.kind) {
    case TMON_FORK: e.kind = EventKind::kFork; break;
    case TMON_EXEC: e.kind = EventKind::kExec; break;
    case TMON_EXIT: e.kind = EventKind::kExit; break;
    case TMON_SYSCALL:
    default: e.kind = EventKind::kSyscall; break;
  }
  e.ts_ns = w.ts_ns;
  e.pid = w.pid;
  e.tid = w.tid;
  e.child_pid = w.child_pid;
  e.syscall_nr = w.syscall_nr;
  e.exit_code = w.exit_code;
  for (int i = 0; i < kSyscallArgs; i++) e.args[i] = w.args[i];
  e.comm.assign(w.comm, ::strnlen(w.comm, TMON_COMM_LEN));
  return e;
}

int HandleRingEvent(void* ctx, void* data, std::size_t size) {
  auto* st = static_cast<PumpState*>(ctx);
  if (size < sizeof(tmon_event)) return 0;
  const auto* w = static_cast<const tmon_event*>(data);

  Event e = ToEvent(*w);
  st->summary.total_events++;
  if (e.kind == EventKind::kSyscall) st->summary.syscall_events++;
  st->pids.insert(e.pid);
  st->sink->Handle(e);

  if (st->max_events != 0 && st->summary.syscall_events >= st->max_events) {
    st->stop = true;
    return 1;  // ask the ring buffer to stop consuming this batch
  }
  return 0;
}

// libbpf emits verbose info/debug chatter by default; keep only warnings so
// tmon's own output stays clean.
int QuietLibbpf(libbpf_print_level level, const char* fmt, va_list args) {
  if (level == LIBBPF_WARN) return vfprintf(stderr, fmt, args);
  return 0;
}

}  // namespace

int Engine::Run(EventSink& sink) {
  if (config_.command.empty()) {
    fprintf(stderr, "tmon: no command to run\n");
    return -1;
  }

  libbpf_set_print(QuietLibbpf);

  tmon_bpf* skel = tmon_bpf__open();
  if (!skel) {
    fprintf(stderr, "tmon: failed to open BPF skeleton\n");
    return -1;
  }
  skel->rodata->follow_children = config_.follow ? 1 : 0;

  if (tmon_bpf__load(skel)) {
    fprintf(stderr, "tmon: failed to load BPF program (need CAP_BPF/root?)\n");
    tmon_bpf__destroy(skel);
    return -1;
  }
  if (tmon_bpf__attach(skel)) {
    fprintf(stderr, "tmon: failed to attach BPF program\n");
    tmon_bpf__destroy(skel);
    return -1;
  }

  PumpState st;
  st.sink = &sink;
  st.max_events = config_.max_events;

  ring_buffer* rb =
      ring_buffer__new(bpf_map__fd(skel->maps.events), HandleRingEvent, &st,
                       nullptr);
  if (!rb) {
    fprintf(stderr, "tmon: failed to create ring buffer\n");
    tmon_bpf__destroy(skel);
    return -1;
  }

  // Spawn the target and stop it before exec so we can seed the filter with its
  // tgid. The child stops itself; the parent seeds the map, then releases it.
  pid_t child = fork();
  if (child < 0) {
    fprintf(stderr, "tmon: fork failed: %s\n", strerror(errno));
    ring_buffer__free(rb);
    tmon_bpf__destroy(skel);
    return -1;
  }

  if (child == 0) {
    // Child: stop ourselves, then exec once the parent releases us. From the
    // parent's SIGCONT onward every syscall (including this execvp) is ours.
    raise(SIGSTOP);
    std::vector<char*> argv;
    argv.reserve(config_.command.size() + 1);
    for (const auto& s : config_.command)
      argv.push_back(const_cast<char*>(s.c_str()));
    argv.push_back(nullptr);
    execvp(argv[0], argv.data());
    // Only reached if exec failed.
    fprintf(stderr, "tmon: exec %s: %s\n", argv[0], strerror(errno));
    _exit(127);
  }

  // Parent: wait for the child to reach its self-inflicted stop, then seed the
  // traced map with its tgid so the tree is followed from birth.
  int wstatus = 0;
  if (waitpid(child, &wstatus, WUNTRACED) < 0) {
    fprintf(stderr, "tmon: waitpid failed: %s\n", strerror(errno));
    ring_buffer__free(rb);
    tmon_bpf__destroy(skel);
    return -1;
  }

  std::uint32_t tgid = static_cast<std::uint32_t>(child);
  std::uint8_t one = 1;
  if (bpf_map__update_elem(skel->maps.traced, &tgid, sizeof(tgid), &one,
                           sizeof(one), 0) != 0) {
    fprintf(stderr, "tmon: failed to seed traced map\n");
    kill(child, SIGKILL);
    ring_buffer__free(rb);
    tmon_bpf__destroy(skel);
    return -1;
  }

  sink.Begin();
  kill(child, SIGCONT);

  // Pump events until the target exits, then drain whatever is left. We poll
  // with a short timeout so we notice the child's exit promptly.
  bool child_gone = false;
  while (!st.stop) {
    int n = ring_buffer__poll(rb, 100 /* ms */);
    if (n < 0 && n != -EINTR) break;

    if (!child_gone) {
      int r = waitpid(child, &wstatus, WNOHANG);
      if (r == child) {
        st.summary.target_exit_code =
            WIFEXITED(wstatus) ? WEXITSTATUS(wstatus) : 128 + WTERMSIG(wstatus);
        child_gone = true;
      }
    } else if (n == 0) {
      // Child is gone and the last poll drained nothing: capture is complete.
      break;
    }
  }

  if (st.stop && !child_gone) {
    kill(child, SIGKILL);
    waitpid(child, &wstatus, 0);
  }

  st.summary.processes = static_cast<std::uint32_t>(st.pids.size());
  sink.End(st.summary);

  ring_buffer__free(rb);
  tmon_bpf__destroy(skel);
  return st.summary.target_exit_code;
}

}  // namespace tmon
