#!/usr/bin/env bash
# Emit a C++ errno-number -> name table to stdout, generated from the host's
# <asm-generic/errno*.h>. Same rationale as the syscall table: build it from the
# system headers so it matches the kernel ABI rather than drifting. Sorted by
# ascending number for binary search.
set -euo pipefail

find_header() {
  echo "#include <$1>" | "${CC:-cc}" -E -M - 2>/dev/null \
    | tr ' ' '\n' | grep "$1" | head -n1 || true
}
base=$(find_header asm-generic/errno-base.h)
ext=$(find_header asm-generic/errno.h)
if [ -z "${base}" ] || [ ! -f "${base}" ]; then
  echo "gen_errno.sh: cannot locate asm-generic/errno-base.h" >&2
  exit 1
fi

echo "// Generated by gen_errno.sh from ${base} ${ext} — do not edit."
echo "struct ErrnoEntry { int num; const char* name; };"
echo "static const ErrnoEntry kErrnoTable[] = {"
# Numeric defines only (aliases like 'EWOULDBLOCK EAGAIN' are non-numeric and
# are skipped). Dedupe by number, keeping the first name for a given value.
grep -hE '^#define[[:space:]]+E[A-Z0-9]+[[:space:]]+[0-9]+' "${base}" "${ext}" 2>/dev/null \
  | sed -E 's/^#define[[:space:]]+(E[A-Z0-9]+)[[:space:]]+([0-9]+).*/\2 \1/' \
  | sort -n -u -k1,1 \
  | awk '{ printf "    { %s, \"%s\" },\n", $1, $2 }'
echo "};"
echo "static const std::size_t kErrnoTableCount ="
echo "    sizeof(kErrnoTable) / sizeof(kErrnoTable[0]);"
