#!/usr/bin/env bash
# Emit a C++ syscall-number -> name table to stdout, generated from the host's
# <asm/unistd_64.h>. Building the table from the system header (rather than
# shipping a static list) keeps it exactly aligned with the kernel ABI tmon is
# compiled against. Output is sorted by ascending syscall number so the lookup
# can binary-search it.
set -euo pipefail

# Ask the compiler where <asm/unistd_64.h> lives, so this works regardless of
# multiarch include layout.
header=$(echo '#include <asm/unistd_64.h>' | "${CC:-cc}" -E -M - 2>/dev/null \
  | tr ' ' '\n' | grep 'unistd_64.h' | head -n1 || true)
if [ -z "${header}" ] || [ ! -f "${header}" ]; then
  echo "gen_syscalls.sh: cannot locate asm/unistd_64.h" >&2
  exit 1
fi

echo "// Generated by gen_syscalls.sh from ${header} — do not edit."
echo "struct SyscallEntry { long nr; const char* name; };"
echo "static const SyscallEntry kSyscallTable[] = {"
# Lines look like: #define __NR_read 0
grep -E '^#define __NR_[a-zA-Z0-9_]+ [0-9]+' "${header}" \
  | sed -E 's/^#define __NR_([a-zA-Z0-9_]+) ([0-9]+).*/\2 \1/' \
  | sort -n -k1,1 \
  | awk '{ printf "    { %s, \"%s\" },\n", $1, $2 }'
echo "};"
echo "static const std::size_t kSyscallTableCount ="
echo "    sizeof(kSyscallTable) / sizeof(kSyscallTable[0]);"
